version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '27081:80'
    container_name: wxcloud_wxcloudrun-express-main
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=wxcloudrun-express-main
      - role=container
    environment:
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_ADDRESS=host.docker.internal:3308
networks:
  default:
    external:
      name: wxcb0
